-- NESA HSC Economics (Stage 6 syllabus, 2009, updated 2011): HSC topics and their content headings.
insert into public.topics (id, parent_id, name, sort) values
  ('t1', null, 'The Global Economy', 1),
  ('t2', null, 'Australia''s Place in the Global Economy', 2),
  ('t3', null, 'Economic Issues', 3),
  ('t4', null, 'Economic Policies and Management', 4),
  ('t1-integration', 't1', 'International economic integration', 1),
  ('t1-trade', 't1', 'Trade, financial flows and foreign investment', 2),
  ('t1-protection', 't1', 'Protection', 3),
  ('t1-development', 't1', 'Globalisation and economic development', 4),
  ('t1-case-study', 't1', 'Case study: globalisation and an economy other than Australia', 5),
  ('t2-trade-flows', 't2', 'Australia''s trade and financial flows', 1),
  ('t2-bop', 't2', 'Australia''s Balance of Payments', 2),
  ('t2-exchange-rates', 't2', 'Exchange rates', 3),
  ('t2-free-trade', 't2', 'Free trade and protection', 4),
  ('t3-growth', 't3', 'Economic growth', 1),
  ('t3-unemployment', 't3', 'Unemployment', 2),
  ('t3-inflation', 't3', 'Inflation', 3),
  ('t3-external-stability', 't3', 'External stability', 4),
  ('t3-distribution', 't3', 'Distribution of income and wealth', 5),
  ('t3-environment', 't3', 'Environmental sustainability', 6),
  ('t4-objectives', 't4', 'Economic objectives', 1),
  ('t4-fiscal', 't4', 'Fiscal policy', 2),
  ('t4-monetary', 't4', 'Monetary policy', 3),
  ('t4-micro', 't4', 'Microeconomic policies', 4),
  ('t4-labour', 't4', 'Labour market policies', 5),
  ('t4-environment', 't4', 'National and global context for environmental management', 6),
  ('t4-limitations', 't4', 'Limitations of economic policies', 7),
  ('t4-responses', 't4', 'Policy responses and their effects', 8);
